version: '2'

services:
   zookeeper:
      image: zookeeper:3.4.9
      hostname: zookeeper
      container_name: zookeeper
      ports:
         - "2181:2181"
      networks:
         - acoesb3-net

   kafka:
      image: confluentinc/cp-kafka:5.4.3
      hostname: kafka
      container_name: kafka
      ports:
         - "9092:9092"
      environment:
         KAFKA_BROKER_ID: 1
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
         KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      depends_on:
         - zookeeper
      networks:
         - acoesb3-net

   web:
      container_name: server-api-flask
      hostname: server-api-flask
      build: .
      ports:
         - "5000:5000"
      volumes:
         - .:/code
      depends_on:
         - kafka
      networks:
         - acoesb3-net

networks:
   acoesb3-net:
      driver: bridge
