-- Criação da tabela de usuários
CREATE TABLE IF NOT EXISTS USUARIOS (
    id BIGSERIAL PRIMARY KEY,
    USU_LOGIN VARCHAR(50) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(100) NOT NULL,
    USU_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    USU_NOME VARCHAR(100) NOT NULL,
    USU_ATIVO BOOLEAN NOT NULL DEFAULT true
);

-- Criação da tabela de ações favoritas
CREATE TABLE IF NOT EXISTS ACOES_FAVORITAS (
    id BIGSERIAL PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL,
    usuario_id BIGINT NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_usuarios_login ON USUARIOS(USU_LOGIN);
CREATE INDEX IF NOT EXISTS idx_usuarios_email ON USUARIOS(USU_EMAIL);
CREATE INDEX IF NOT EXISTS idx_acoes_favoritas_usuario ON ACOES_FAVORITAS(usuario_id);
CREATE INDEX IF NOT EXISTS idx_acoes_favoritas_codigo ON ACOES_FAVORITAS(codigo); 